#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t AOKP"

$L "_ _                                       "
$L "| (_)_ __   ___  __ _  __ _  ___  ___  ___ "
$L "| | | '_ \\ / _ \\/ _\` |/ _\` |/ _ \\/ _ \\/ __|"
$L "| | | | | |  __/ (_| | (_| |  __/ (_) \\__ \\"
$L "|_|_|_| |_|\\___|\\__,_|\\__, |\\___|\\___/|___/"
$L "                      |___/"
$L "A wise man never plays leapfrog with a unicorn `getprop ro.build.version.release` / AOKP-`getprop ro.aokp.version`";
