PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/a510.mk \
    $(LOCAL_DIR)/amami.mk \
    $(LOCAL_DIR)/anzu.mk \
    $(LOCAL_DIR)/coconut.mk \
    $(LOCAL_DIR)/d2lte.mk \
    $(LOCAL_DIR)/d800.mk \
    $(LOCAL_DIR)/d801.mk \
    $(LOCAL_DIR)/d802.mk \
    $(LOCAL_DIR)/dogo.mk \
    $(LOCAL_DIR)/e980.mk \
    $(LOCAL_DIR)/evita.mk \
    $(LOCAL_DIR)/find5.mk \
    $(LOCAL_DIR)/grouper.mk \
    $(LOCAL_DIR)/haida.mk \
    $(LOCAL_DIR)/hallon.mk \
    $(LOCAL_DIR)/hercules.mk \
    $(LOCAL_DIR)/honami.mk \
    $(LOCAL_DIR)/huashan.mk \
    $(LOCAL_DIR)/hlte.mk \
    $(LOCAL_DIR)/i605.mk \
    $(LOCAL_DIR)/i9100.mk \
    $(LOCAL_DIR)/i9100g.mk \
    $(LOCAL_DIR)/i9300.mk \
    $(LOCAL_DIR)/i9500.mk \
    $(LOCAL_DIR)/iyokan.mk \
    $(LOCAL_DIR)/jflte.mk \
    $(LOCAL_DIR)/l900.mk \
    $(LOCAL_DIR)/ls980.mk \
    $(LOCAL_DIR)/m7.mk \
    $(LOCAL_DIR)/m7spr.mk \
    $(LOCAL_DIR)/m7vzw.mk \
    $(LOCAL_DIR)/m8.mk \
    $(LOCAL_DIR)/maguro.mk \
    $(LOCAL_DIR)/mako.mk \
    $(LOCAL_DIR)/mango.mk \
    $(LOCAL_DIR)/manta.mk \
    $(LOCAL_DIR)/maserati.mk \
    $(LOCAL_DIR)/mint.mk \
    $(LOCAL_DIR)/moto_msm8960dt.mk \
    $(LOCAL_DIR)/odin.mk \
    $(LOCAL_DIR)/p930.mk \
    $(LOCAL_DIR)/pollux.mk \
    $(LOCAL_DIR)/pollux_windy.mk \
    $(LOCAL_DIR)/satsuma.mk \
    $(LOCAL_DIR)/smultron.mk \
    $(LOCAL_DIR)/solana.mk \
    $(LOCAL_DIR)/spyder.mk \
    $(LOCAL_DIR)/su640.mk \
    $(LOCAL_DIR)/targa.mk \
    $(LOCAL_DIR)/t0lte.mk \
    $(LOCAL_DIR)/tilapia.mk \
    $(LOCAL_DIR)/togari.mk \
    $(LOCAL_DIR)/toro.mk \
    $(LOCAL_DIR)/toroplus.mk \
    $(LOCAL_DIR)/tsubasa.mk \
    $(LOCAL_DIR)/umtsspyder.mk \
    $(LOCAL_DIR)/urushi.mk \
    $(LOCAL_DIR)/vs920.mk \
    $(LOCAL_DIR)/vs980.mk \
    $(LOCAL_DIR)/yuga.mk
