#!/bin/sh

# Copyright (C) 2018 AOKP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exports

. $ANDROID_BUILD_TOP/vendor/aokp/tools/colors

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <pathname>" >&2
	exit 1
fi
f="$1"

touch "$f"

# Print something to build output
echo ${bldppl}"Generating changelog..."${txtrst}

for i in $(seq 5); do
	export After_Date=`date --date="$i days ago" +%m-%d-%Y`
	k=$(expr $i - 1)
	export Until_Date=`date --date="$k days ago" +%m-%d-%Y`

	# Line with after --- until was too long for a small ListView
	echo '====================' >> "$f"
	echo  "     "$Until_Date       >> "$f"
	echo '===================='	>> "$f"
	echo >> "$f"

	# Cycle through every repo to find commits between 2 dates
	repo forall -pc 'git log --oneline --after=$After_Date --until=$Until_Date' |
		sed 's/^project/   */' >> "$f"
	echo >> "$f"
done
