#!/bin/bash
########################################
#
# AOKP commands for otatools enhancement
# .:BMc08GT:.
#
########################################

# Colors
if [ ! "$BUILD_WITH_COLORS" = "0" ]; then
    CL_RED="\033[31m"
    CL_GRN="\033[32m"
    CL_YLW="\033[33m"
    CL_BLU="\033[34m"
    CL_MAG="\033[35m"
    CL_CYN="\033[36m"
    CL_RST="\033[0m"
fi

# Date
GETDATE="$( shell LC_ALL=C date +%h-%d-%y)"

# Zip Size
ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
