#!/bin/bash
#
# Squish a CM otapackage for distribution
#
# cyanogen
# AOKP

. $ANDROID_BUILD_TOP/vendor/aokp/tools/colors

OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   OUT_TARGET_HOST=linux-x86
   MD5=md5sum
   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
   SED=sed
else
   OUT_TARGET_HOST=darwin-x86
   MD5="md5 -r "
   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
   SED=gsed
fi

if [ -z "$OUT" -o ! -d "$OUT" ]; then
	echo -e "ERROR: $0 only works with a full build environment. $OUT should exist."
	exit 1
fi

if [ ! -f "$OTAPACKAGE" ]; then
	echo -e "$OTAPACKAGE doesn't exist!";
	exit 1
fi

#MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
VERSION=`sed -n -e'/ro.aokp.version/s/^.*=//p' $OUT/system/build.prop`
MODVERSION="$VERSION"
OUTFILE=$OUT/$MODVERSION.zip

ln -f $OTAPACKAGE $OUTFILE

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
$MD5 $img >$img.md5sum
ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
echo -e
echo -e $CL_RED"    ______"$CL_MAG"  _____"$CL_CYN"   __  __"$CL_BLU"   ____"$CL_RST
echo -e $CL_RED"   /\\\\  _  \\\\"$CL_MAG"/\\\\  __\`\\\\"$CL_CYN"/\\\\ \\\\/\\\\ \\\\"$CL_BLU" /\\\\  _\`\\\\"$CL_RST
echo -e $CL_RED"   \\\\ \\\\ \\\\L\\\\ \\\\"$CL_MAG" \\\\ \\\\/\\\\ \\\\"$CL_CYN" \\\\ \\\\/'/'"$CL_BLU"\\\\ \\\\ \\\\L\\\\ \\\\"$CL_RST
echo -e $CL_RED"    \\\\ \\\\  __ \\\\"$CL_MAG" \\\\ \\\\ \\\\ \\\\"$CL_CYN" \\\\ , <"$CL_BLU"  \\\\ \\\\ ,__/"$CL_RST
echo -e $CL_RED"     \\\\ \\\\ \\\\/\\\\ \\\\"$CL_MAG" \\\\ \\\\_\\\\ \\\\"$CL_CYN" \\\\ \\\\\\\\\`\\\\"$CL_BLU" \\\\ \\\\ \\\\/"$CL_RST
echo -e $CL_RED"      \\\\ \\\\_\\\\ \\\\_\\\\"$CL_MAG" \\\\_____\\\\"$CL_CYN" \\\\_\\\\ \\\\_\\\\"$CL_BLU"\\\\ \\\\_\\\\"$CL_RST
echo -e $CL_RED"       \\\\/_/\\\\/_/"$CL_MAG"\\\\/_____/"$CL_CYN"\\\\/_/\\\\/_/"$CL_BLU" \\\\/_/"$CL_RST
echo -e
echo -e $CL_CYN"===========-Package complete-==========="$CL_RST
echo -e $CL_CYN"zip:"$CL_MAG" $OUTFILE"$CL_RST
echo -e $CL_CYN"md5:"$CL_MAG" $(cat $img.md5sum | awk '{ print $1 }')"$CL_RST
echo -e $CL_CYN"size:"$CL_MAG" $ZIPSIZE"$CL_RST
echo -e $CL_CYN"========================================"$CL_RST
echo -e
)

exit 0
